### ISSUE TITLE
Resource for requests that modify, like POST/PUT/PATCH?

### ISSUE THREAD

**Issue by gangefors** [salrashid123/terraform-provider-http-full#14]
I'm trying to use this provider since it can do POST/PUT/PATCH and other modifying REST requests, but I don't want the requests executed when running `terraform plan`. As it stands now, this provider will make modifying requests during the planning phase, which I would not expect from a Data Source. I can however see that it would in the current form since there is no differentiation between methods.

Would it be possible to provide a Resource that only executes the requests during the `terraform apply` phase?

I would also recommend adding a warning in the docs that requests will execute during the planning, so using methods that modify resources should be avoided when used as a Data Source.

**Comment by salrashid123** [comment]
i havne't tried it but this provides a rest resource 
 https://registry.terraform.io/providers/Mastercard/restapi/latest

**Comment by gangefors** [comment]
Ah, thanks for the tip. That might be a better fit for me.
