### ISSUE TITLE
Support arbitrary request_body for JSON POST requests

### ISSUE THREAD

**Issue by dinvlad** [salrashid123/terraform-provider-http-full#3]
Hi @salrashid123,

I'm trying to use this provider to make a request to Google Cloud Resource Manager API (since there's no `google_project_iam` data source [yet](https://github.com/hashicorp/terraform-provider-google/issues/9516)):
```tf
data "google_project" "project" {}
data "google_client_config" "client" {}

data "http" "project_iam_policy" {
  provider = http-full

  url = "https://cloudresourcemanager.googleapis.com/v3/projects/${data.google_project.project.project_id}:getIamPolicy"

  request_body = {}
  request_headers = {
    Authorization = "Bearer ${data.google_client_config.client.access_token}"
    Content-Type = "application/json"
  }
}
```
However, that doesn't work as I get back a `404` error, indicating it is not making a `POST` in this case. The [API call in question](https://cloud.google.com/resource-manager/reference/rest/v3/projects/getIamPolicy) is unfortunately a `POST` request, accepting an empty body, or optionally a body with some nested objects. However, I could not make it work with a non-empty body either:
```tf
  request_body = {
    options = {
      requestedPolicyVersion = 3
    }
  }
```
then Terraform complains about `"request_body": element "options": string required`, so I think nested objects like these are not supported either.. I've also tried:
```tf
  request_body = {
    options = jsonencode({
      requestedPolicyVersion = 3
    })
  }
```
but then Google API complains about `"Invalid JSON payload received. Unknown name \"{\"options\":\"{\\\"requestedPolicyVersion\\\":3}\"}\": Cannot bind query parameter. Field '{\"options\":\"{\\\"requestedPolicyVersion\\\":3}\"}' could not be found in request message."`, so it doesn't like the JSON encoding for `options`..

The workaround I found for now in this particular case is:
```tf
  request_body = {
    body = ""
  }
  request_headers = {
    Authorization = "Bearer ${local.google_client.access_token}"
    Content-Type  = "application/x-www-form-urlencoded" # needed for http-full to provide empty body
  }
```
but this is not ideal.

Is there a way to support arbitrary shape of `request_body`, including an empty one? For example, [here](https://github.com/salrashid123/terraform-provider-http-full/blob/b316f9230e4bd7ee2e117bf4d6291300ec22e24e/internal/provider/data_source.go#L42-L48):
```go
			"request_body": {
				Type:     schema.TypeMap,
				Optional: true,
				Elem: &schema.Schema{
					Type: schema.TypeMap,
				},
			},
```

Thanks!

**Comment by salrashid123** [comment]
hi-

thanks for the note.  you're right, i didn't think to allow encoded/nested json in the post.

I think at a minimum, i'd need a `method` parameter below too to allow the override

The second part is harder in how to post nested json as a struct..i'll have to do some research on how thats done...if you have any thoughts, LMK

eg somehow allow arbitrary json in the terraform definition (i'm not even sure thats allowed or not...)

```hcl
  request_body = {
    options = {
      requestedPolicyVersion = 3
    }
  }
```

i made the request_body optional with the verb override, i was able to recall data from `getIamPolicy`


```hcl
provider "http-full" {
}

data "http" "project_iam_policy" {
  provider = http-full
  url = "https://cloudresourcemanager.googleapis.com/v3/projects/${data.google_project.project.project_id}:getIamPolicy"

  method = "POST"

  request_headers = {
    Authorization = "Bearer ${data.google_client_config.client.access_token}"
    Content-Type = "application/json"
  }
}
```

**Comment by salrashid123** [comment]
ok, how about  this:

the `request_body` becomes a  string value outright 

```golang
			"request_body": {
				Type:     schema.TypeString,
				Computed: false,
				Optional: true,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
```

which would make the usage like this:

```hcl
data "http" "example_json" {
  provider = http-full
  url = "https://localhost:8081/post"

  method = "POST"
  request_headers = {
    content-type = "application/json"
  }

  request_body = jsonencode({foo = "bar",bar = "bar"})
}
```

or

```hcl
data "http" "example_form" {
  provider = http-full
  url = "https://localhost:8081/post"

  method = "POST"
  request_headers = {
    content-type = "application/x-www-form-urlencoded"
  }

  request_body = "foo=bar&bar=bar"
}
```

 @dutsmiller FYI since its a breaking change here, unfortunately

**Comment by salrashid123** [comment]
@dinvlad applied these changes to `1.2.0`:
  which is now on the registry

**Comment by dinvlad** [comment]
Oh wow, thanks so much! Yes that works much better :smiley:
