### ISSUE TITLE
Increase maximum request_body size (=> grpc message size)

### ISSUE THREAD

**Issue by adaptivegarage** [salrashid123/terraform-provider-http-full#8]
Hi,
my Terraform configuration depends on your provider plugin, as I think it is the only one that supports POST method and request body. I use it to send requests to a REST API.
Unfortunately though, the bodies of some of my requests are larger than the Terraform GRPC message limit of 4MB.

I understand from this post that the limit could be increased:
https://support.hashicorp.com/hc/en-us/articles/4803097239955-gRPC-message-larger-than-max-error

```
The feature update to increase the size to 256MB has been implemented in terraform-plugin-go v0.6.0 and is used by the terraform-plugin-sdk.
However, this update has not been adopted by the provider plugins yet.
```

Would you please consider this?
Thank you.

**Comment by salrashid123** [comment]
ok, i bumped the tf dependency and was able to test POST with a 6mb file.

can you try out with

```hcl
terraform {
  required_providers {
    http-full = {
      source = "salrashid123/http-full"
      version = "1.3.0"
    }
  }
}

```

**Comment by adaptivegarage** [comment]
> ok, i bumped the tf dependency and was able to test POST with a 6mb file.
> 
> can you try out with
> 
> ```terraform
> terraform {
>   required_providers {
>     http-full = {
>       source = "salrashid123/http-full"
>       version = "1.3.0"
>     }
>   }
> }
> ```

Hi,
I am impressed by your speed and attention.
Big thumbs up, it works.
Thank you very much.
R.
